# Generated by Django 4.2.3 on 2024-03-12 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security_Question',
            fields=[
                ('questionID', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('security_question_answer', models.CharField(max_length=100)),
                ('date_reminder', models.DateField(null=True)),
                ('security_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.security_question')),
            ],
        ),
        migrations.CreateModel(
            name='Password_History',
            fields=[
                ('password', models.CharField(max_length=50)),
                ('passwordID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_histories', to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('groceryID', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceries', to='home.user')),
            ],
        ),
    ]
