# Generated by Django 4.2.3 on 2024-03-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
