# Generated by Django 4.2.3 on 2024-03-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_user_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
