# Generated by Django 4.2.3 on 2024-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='unit',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
