# Generated by Django 4.2.3 on 2024-03-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_grocery_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='custom_reminder',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='day_before',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='grocery',
            name='is_expired',
            field=models.BooleanField(default='False'),
        ),
    ]
