# Generated by Django 4.2.3 on 2024-03-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_recipe_remove_security_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(max_length=750),
        ),
    ]
